**Rename this file to `secrets.toml` and add your API keys**

WEAVIATE_URL = "add-your-weaviate-url-here"
WEAVIATE_API_KEY = "add-your-weaviate-api-key-here"
OPENAI_API_KEY = "add-your-openai-api-key-here"